context:
  name: ocaml
  version: 2.50

package:
  name: opam
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/opam/releases/download/{{ version }}/opam-full-{{ version }}.tar.gz
    sha256: 25fb98f962c4227c1261e142afc68a416778e6e819600bd5ee3ec4a18ae1e238

build:
  # number: 0
  # prefix_detection:
  #   force_file_type:
  #     text:
  #       - lib/ocaml/runtime-launch-info
  #   ignore:
  #     # Ignore all but run* and ld.*
  #     - lib/ocaml/[^rl][^ud][^n\.]*
  #     - bin/*

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ocaml >=5.3.0
    - make
    - patch
    - ocamlbuild
    - ocaml-findlib
  host:
  run:
    - rsync
    - git
    - mercurial
    - m4
    - diffutils
    - unzip
    - patch
    - if: linux
      then:
        - bubblewrap

tests:
  - package_contents:
      bin:
        - opam

  - script:
      - opam

about:
  homepage: https://github.com/ocaml/opam
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    opam is a source-based package manager. It supports multiple simultaneous compiler
    installations, flexible package constraints, and a Git-friendly development workflow.
  repository: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - dslarm
    - fasiha
    - MementoRC
