context:
  name: opam
  version: 2.5.0
  library: ${{ "Library/" if not unix }}
  m2: ${{ "m2-" if not unix }}
  sh: ${{ "sh" if unix else "bat" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/${{ name }}/releases/download/${{ version }}/${{ name }}-full-${{ version }}.tar.gz
    sha256: 25fb98f962c4227c1261e142afc68a416778e6e819600bd5ee3ec4a18ae1e238

build:
  number: 1
  dynamic_linking:
    missing_dso_allowlist:
      - if: not unix
        then:
          - C:/Windows/system32/SHLWAPI.dll
          - C:/Windows/system32/VERSION.dll

requirements:
  build:
    - if: unix
      then:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
      else:
        - ${{ compiler("m2w64_c") }}
        - ${{ compiler("m2w64_cxx") }}
        - ${{ stdlib("m2w64_c") }}
    - ${{ m2 }}bash >=5.2
    - ${{ m2 }}bzip2
    - ${{ m2 }}findutils
    - ${{ m2 }}gawk
    - ${{ m2 }}grep
    - ${{ m2 }}make
    - ${{ m2 }}sed
    - binutils
    - curl
    - git
    - ocaml >=5.3.0
    - if: unix
      then:
        # OCaml compiler has zstd paths embedded from its build environment.
        # We need zstd in build env so those paths resolve correctly.
        - file
        - unzip
        - zstd
      else:
        - ${{ m2 }}coreutils
        - ${{ m2 }}diffutils
        - ${{ m2 }}which
    - if: osx
      then:
        - lld
        - llvm-tools
  host:
    - if: aarch64 or ppc64le
      then:
        - zstd
  run:
    - c-compiler
    - curl
    - git
    - if: unix
      then:
        - make
        - rsync
        - unzip
    - if: linux
      then:
        - bubblewrap
      # Once we have ocaml 5.4.0 _1
      # - ocaml-compiler

tests:
  # 1. Package contents validation
  - package_contents:
      strict: true
      bin:
        - opam
        - opam-installer
      files:
        - etc/conda/activate.d/opam-activate.${{ sh }}
        - etc/conda/deactivate.d/opam-deactivate.${{ sh }}
        - ${{ library }}share/man/man1/opam*
        - ${{ library }}share/opam/conda/.opam-switch/{environment,lock,switch-config}
        - ${{ library }}share/opam/config
        - ${{ library }}share/opam/config.lock
        - ${{ library }}share/opam/lock
        - ${{ library }}share/opam/opam-init/complete.{sh,zsh}
        - ${{ library }}share/opam/opam-init/hooks/sandbox.{sh,sh.hash}
        - ${{ library }}share/opam/opam-init/init.{cmd,csh,fish,ps1,sh,zsh}
        - ${{ library }}share/opam/opam-init/variables.{cmd,csh,fish,ps1,sh}
        - ${{ library }}share/opam/repo/default/repo
        - ${{ library }}share/opam/repo/lock
        - ${{ library }}share/opam/repo/repos-config
        - if: unix and build_platform == target_platform
          then:
            - ${{ library }}share/opam/conda/.opam-switch/packages/cache

        - etc/conda/test-files/opam/*

  - script: |
      python testing/test-opam-version.py || true
      python testing/test-opam-functional.py || true
      python testing/test-opam-activation.py || true
    files:
      recipe:
        - testing/test-opam-version.py
        - testing/test-opam-functional.py
        - testing/test-opam-activation.py
    requirements:
      run:
        - python >=3.9
        - ocaml

about:
  homepage: https://github.com/ocaml/opam
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    opam is a source-based package manager. It supports multiple simultaneous compiler
    installations, flexible package constraints, and a Git-friendly development workflow.
  repository: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - dslarm
    - fasiha
    - MementoRC
