context:
  name: opam
  version: 2.5.0
  library: ${{ "Library/" if not unix }}
  m2: ${{ "m2-" if not unix }}
  sh: ${{ "sh" if unix else "bat" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/${{ name }}/releases/download/${{ version }}/${{ name }}-full-${{ version }}.tar.gz
    sha256: 25fb98f962c4227c1261e142afc68a416778e6e819600bd5ee3ec4a18ae1e238

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ${{ m2 }}bash >=5.2
    - ${{ m2 }}bzip2
    - ${{ m2 }}findutils
    - ${{ m2 }}gawk
    - ${{ m2 }}grep
    - ${{ m2 }}make
    - ${{ m2 }}sed
    - binutils
    - curl
    - git
    - ocaml >=5.3.0
    - if: unix
      then:
        # OCaml compiler has zstd paths embedded from its build environment.
        # We need zstd in build env so those paths resolve correctly.
        - file
        - unzip
        - zstd
      else:
        - ${{ m2 }}coreutils
        - ${{ m2 }}diffutils
        - ${{ m2 }}which
    - if: osx
      then:
        - lld
        - llvm-tools
  host:
  - if: aarch64 or ppc64le
    then:
      - zstd
  run:
    - c-compiler
    - curl
    - git
    - if: unix
      then:
        - make
        - rsync
        - unzip
    - if: linux
      then:
        - bubblewrap
      # Once we have ocaml 5.4.0_1
      # - ocaml-compiler

tests:
  - package_contents:
      strict: true
      bin:
        - opam
        - opam-installer
      files:
        - ${{ library }}share/man/man1/opam*
        - etc/conda/activate.d/opam-activate.${{ sh }}
        - etc/conda/deactivate.d/opam-deactivate.${{ sh }}
        - ${{ library }}share/opam/conda/.opam-switch/environment
        - ${{ library }}share/opam/conda/.opam-switch/lock
        - ${{ library }}share/opam/conda/.opam-switch/switch-config
        - ${{ library }}share/opam/config
        - ${{ library }}share/opam/config.lock
        - ${{ library }}share/opam/lock
        - ${{ library }}share/opam/opam-init/complete.sh
        - ${{ library }}share/opam/opam-init/complete.zsh
        - ${{ library }}share/opam/opam-init/hooks/sandbox.sh
        - ${{ library }}share/opam/opam-init/hooks/sandbox.sh.hash
        - ${{ library }}share/opam/opam-init/init.cmd
        - ${{ library }}share/opam/opam-init/init.csh
        - ${{ library }}share/opam/opam-init/init.fish
        - ${{ library }}share/opam/opam-init/init.ps1
        - ${{ library }}share/opam/opam-init/init.sh
        - ${{ library }}share/opam/opam-init/init.zsh
        - ${{ library }}share/opam/opam-init/variables.cmd
        - ${{ library }}share/opam/opam-init/variables.csh
        - ${{ library }}share/opam/opam-init/variables.fish
        - ${{ library }}share/opam/opam-init/variables.ps1
        - ${{ library }}share/opam/opam-init/variables.sh
        - ${{ library }}share/opam/repo/default/repo
        - ${{ library }}share/opam/repo/lock
        - ${{ library }}share/opam/repo/repos-config
        - if: unix and build_platform == target_platform
          then:
            - ${{ library }}share/opam/conda/.opam-switch/packages/cache

  - script:
      - if: build_platform == target_platform
        then: |
            opam --version | grep ${{ version }}
        else: |
            echo "OCaml 5.x GC segfaults under QEMU"
    requirements:
      run:
        - ${{ m2 }}grep

  # Functional tests - exercise core opam functionality to catch build issues
  # (broken linking, missing libraries, OCaml runtime problems)
  # Unix: bash. Windows: powershell (avoids WSL/MSYS2 PATH issues).
  # Cross-compile: skipped (QEMU + OCaml 5.x GC incompatibility).
  - script:
      - if: unix and build_platform == target_platform
        then: |
          export OPAMROOT=./opam_test
          export OPAMSWITCH=
          mkdir -p opam_test
          opam init --bare --no-setup --bypass-checks --disable-sandboxing
          opam config list
          opam switch create test --empty
          eval $(opam env --switch=test)
          opam list --installed
          opam switch list
          opam switch remove test --yes
          rm -rf opam_test
      - if: unix and build_platform != target_platform
        then: |
          echo "Skipping functional tests (cross-compile: QEMU + OCaml 5.x GC issue)"

  - script:
      - if: win
        then:
          interpreter: powershell
          content: |
            $env:OPAMROOT = "./opam_test"
            New-Item -ItemType Directory -Force -Path opam_test
            opam init --bare --no-setup --bypass-checks
            opam config list
            opam switch create test --empty
            opam list --installed
            opam switch list
            opam switch remove test --yes
            Remove-Item -Recurse -Force opam_test

  # Activation script integration tests
  # Conda runs activate.d scripts automatically before tests, so env vars
  # should already be set. The opam root is pre-initialized at build time.
  - script:
      - if: unix and build_platform == target_platform
        then: |
          # Verify activation set correct env vars
          test "$OPAMROOT" = "$CONDA_PREFIX/share/opam"
          test "$OPAMSWITCH" = "conda"
          test "$OPAMNOENVNOTICE" = "true"
          # Verify pre-initialized opam root
          test -d "$OPAMROOT"
          test -d "$OPAMROOT/conda/.opam-switch"
          # Verify opam recognizes the switch
          opam switch list | grep conda
      - if: unix and build_platform != target_platform
        then: |
          echo "Skipping activation tests (cross-compile)"
  - script:
      - if: win
        then:
          content: |
            REM Verify activation set correct env vars (conda ran activate.bat automatically)
            if not "%OPAMROOT%"=="%CONDA_PREFIX%\share\opam" exit /b 1
            if not "%OPAMSWITCH%"=="conda" exit /b 1
            if not "%OPAMNOENVNOTICE%"=="true" exit /b 1
            REM Verify pre-initialized opam root
            if not exist "%OPAMROOT%" exit /b 1
            if not exist "%OPAMROOT%\conda\.opam-switch" exit /b 1
            REM Verify opam sees the switch
            opam switch list | findstr "conda" >nul || exit /b 1

about:
  homepage: https://github.com/ocaml/opam
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    opam is a source-based package manager. It supports multiple simultaneous compiler
    installations, flexible package constraints, and a Git-friendly development workflow.
  repository: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - dslarm
    - fasiha
    - MementoRC
