context:
  name: ocaml
  version: 2.5.0

package:
  name: opam
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/opam/releases/download/${{ version }}/opam-full-${{ version }}.tar.gz
    sha256: 25fb98f962c4227c1261e142afc68a416778e6e819600bd5ee3ec4a18ae1e238

build:
  number: 0

requirements:
  build:
    - curl
    - ocaml >=5.3.0
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - make
        - patch
      else:
        - ${{ compiler('m2w64_c') }}
        - ${{ compiler('m2w64_cxx') }}
        - ${{ stdlib('m2w64_c') }}
        - m2-bash
        - m2-make

    # We need to 2-phase as these do not exist yet for arm64 and non-unix
    # We add opam bare for all archs, then later we update below
    # - ocamlbuild
    # - ocaml-findlib
    
  host:
  run:
    - rsync
    - git
    - mercurial
    - if: unix
      then:
        - diffutils
        - m4
        - patch
        - unzip
      else:
        - m2-diffutils
        - m2-m4
    - if: linux
      then:
        - bubblewrap

tests:
  - package_contents:
      bin:
        - opam

  - script:
      - opam

about:
  homepage: https://github.com/ocaml/opam
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    opam is a source-based package manager. It supports multiple simultaneous compiler
    installations, flexible package constraints, and a Git-friendly development workflow.
  repository: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - dslarm
    - fasiha
    - MementoRC
